<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7SBKKJ1" failures="20" tests="67" name="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" time="285.166" errors="0" timestamp="2024-09-13T10:59:01 IST" skipped="0">
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Username" time="2.236"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Password" time="3.319"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Captcha" time="3.298"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="SUBMIT_Button" time="10.159"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Click_On_Report" time="9.377"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Click_On_The_SMR_Due_date_Wise" time="3.198"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Zone_Region_Wise" time="48.528"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Dealer_Parent_Group_Wise" time="49.959"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="WorkShop_Wise" time="54.944"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Day_Wise" time="50.076"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Service_Type_Wise" time="47.983"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Data_Assigned_of_ZONE_and_Region_with_Dealer_Parent_Group_Wise" time="0.007"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Data_Assigned_of_ZONE_and_Region_with_WorkShop_Wise" time="0.001"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Data_Assigned_of_ZONE_and_Region_with_Day_Wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Data_Assigned_of_ZONE_and_Region_with_Service_type_Wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_ReportedAtOWN_of_ZONE_and_Region_with_Dealer_Parent_Group_Wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_ReportedAtOWN_of_ZONE_and_Region_with_WorkShop_Wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_ReportedAtOWN_of_ZONE_and_Region_with_Day_Wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_ReportedAtOWN_of_ZONE_and_Region_with_Service_type_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_ReportedAt_Same_Parent_Other_Outlet_of_ZONE_and_Region_with_workshopwise_wise" time="0.016"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_ReportedAt_Same_Parent_Other_Outlet_of_ZONE_and_Region_with_Dealer_parent_group_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_ReportedAt_Same_Parent_Other_Outlet_of_ZONE_and_Region_with_Day_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_ReportedAt_Same_Parent_Other_Outlet_of_ZONE_and_Region_with_service_type__wise" time="0.002"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Reported_At_Other_of_ZONE_and_Region_with_Dealer_parent_group_wise" time="0.002">
    <failure message="expected [8343] but found [3102]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [8343] but found [3102]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_Reported_At_Other_of_ZONE_and_Region_with_Dealer_parent_group_wise(SMR_Due_Date_Wise_Central.java:597)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Reported_At_Other_of_ZONE_and_Region_with_Dealer_parent_group_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Reported_At_Other_of_ZONE_and_Region_with_Workshop_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Reported_At_Other_of_ZONE_and_Region_with_service_type_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Reported_At_Other_of_ZONE_and_Region_with_Day_wise" time="0.000">
    <failure message="expected [8343] but found [3102]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [8343] but found [3102]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_Reported_At_Other_of_ZONE_and_Region_with_Day_wise(SMR_Due_Date_Wise_Central.java:611)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Reported_At_Other_of_ZONE_and_Region_with_Day_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Wrong_Number_of_ZONE_and_Region_with_Dealer_parent_group_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Appointment_Booked_of_ZONE_and_Region_with_Dealer_parent_group_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Wrong_Number_of_ZONE_and_Region_with_Worshop_wise" time="0.003"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Appointment_Booked_of_ZONE_and_Region_with_Worshop_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Wrong_Number_of_ZONE_and_Region_with_Day_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Appointment_Booked_of_ZONE_and_Region_with_Day_wise" time="0.000">
    <failure message="expected [11317] but found [11316]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [11317] but found [11316]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_Appointment_Booked_of_ZONE_and_Region_with_Day_wise(SMR_Due_Date_Wise_Central.java:639)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Appointment_Booked_of_ZONE_and_Region_with_Day_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Wrong_Number_of_ZONE_and_Region_with_service_type_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Appointment_Booked_of_ZONE_and_Region_with_service_type_wise" time="0.012">
    <failure message="expected [11317] but found [11316]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [11317] but found [11316]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_Appointment_Booked_of_ZONE_and_Region_with_service_type_wise(SMR_Due_Date_Wise_Central.java:646)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Appointment_Booked_of_ZONE_and_Region_with_service_type_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_call_Me_Later_of_ZONE_and_Region_with_Dealer_parent_Group_wise" time="0.000">
    <failure message="expected [30714] but found [30715]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [30714] but found [30715]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_call_Me_Later_of_ZONE_and_Region_with_Dealer_parent_Group_wise(SMR_Due_Date_Wise_Central.java:652)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_call_Me_Later_of_ZONE_and_Region_with_Dealer_parent_Group_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Appointmment_Cancelled_of_ZONE_and_Region_with_Dealer_parent_Group_wise" time="0.006"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Appointmment_Cancelled_of_ZONE_and_Region_with_Workshop_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_call_Me_Later_of_ZONE_and_Region_with_Workshop_wise" time="0.000">
    <failure message="expected [11316] but found [30715]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [11316] but found [30715]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_call_Me_Later_of_ZONE_and_Region_with_Workshop_wise(SMR_Due_Date_Wise_Central.java:658)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_call_Me_Later_of_ZONE_and_Region_with_Workshop_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Appointmment_Cancelled_of_ZONE_and_Region_with_Day_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_call_Me_Later_of_ZONE_and_Region_with_Day_wise" time="0.000">
    <failure message="expected [30711] but found [30715]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [30711] but found [30715]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_call_Me_Later_of_ZONE_and_Region_with_Day_wise(SMR_Due_Date_Wise_Central.java:664)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_call_Me_Later_of_ZONE_and_Region_with_Day_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_call_Not_Connected_of_ZONE_and_Region_with_Dealer_parent_group_wise" time="0.000">
    <failure message="expected [31836] but found [31834]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [31836] but found [31834]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_call_Not_Connected_of_ZONE_and_Region_with_Dealer_parent_group_wise(SMR_Due_Date_Wise_Central.java:803)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_call_Not_Connected_of_ZONE_and_Region_with_Dealer_parent_group_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_call_Me_Later_of_ZONE_and_Region_with_Service_type_wise" time="0.000">
    <failure message="expected [30711] but found [30715]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [30711] but found [30715]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_call_Me_Later_of_ZONE_and_Region_with_Service_type_wise(SMR_Due_Date_Wise_Central.java:670)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_call_Me_Later_of_ZONE_and_Region_with_Service_type_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Low_Mileage_of_ZONE_and_Region_with_Dealer_parent_group_wise" time="0.002"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Appointmment_Cancelled_of_ZONE_and_Region_with_Service_type_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_call_Not_Connected_of_ZONE_and_Region_with_Workshop_wise" time="0.000">
    <failure message="expected [31839] but found [31834]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [31839] but found [31834]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_call_Not_Connected_of_ZONE_and_Region_with_Workshop_wise(SMR_Due_Date_Wise_Central.java:809)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_call_Not_Connected_of_ZONE_and_Region_with_Workshop_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Low_Mileage_of_ZONE_and_Region_with_Workshop_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_call_Not_Connected_of_ZONE_and_Region_with_Day_wise" time="0.000">
    <failure message="expected [31841] but found [31834]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [31841] but found [31834]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_call_Not_Connected_of_ZONE_and_Region_with_Day_wise(SMR_Due_Date_Wise_Central.java:815)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_call_Not_Connected_of_ZONE_and_Region_with_Day_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Low_Mileage_of_ZONE_and_Region_with_Day_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Low_Mileage_of_ZONE_and_Region_with_Service_type_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_call_Not_Connected_of_ZONE_and_Region_with_Service_type_wise" time="0.000">
    <failure message="expected [31843] but found [31834]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [31843] but found [31834]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_call_Not_Connected_of_ZONE_and_Region_with_Service_type_wise(SMR_Due_Date_Wise_Central.java:821)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_call_Not_Connected_of_ZONE_and_Region_with_Service_type_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_vehicle_sold_to_New_Owner_of_ZONE_and_Region_with_Dealer_parent_group_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Fresh_of_ZONE_and_Region_with_Dealer_parent_group_wise" time="0.000">
    <failure message="expected [0] but found [416]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [0] but found [416]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_Fresh_of_ZONE_and_Region_with_Dealer_parent_group_wise(SMR_Due_Date_Wise_Central.java:828)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Fresh_of_ZONE_and_Region_with_Dealer_parent_group_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Fresh_of_ZONE_and_Region_with_workshop_wise" time="0.000">
    <failure message="expected [0] but found [416]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [0] but found [416]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_Fresh_of_ZONE_and_Region_with_workshop_wise(SMR_Due_Date_Wise_Central.java:834)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Fresh_of_ZONE_and_Region_with_workshop_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_vehicle_sold_to_New_Owner_of_ZONE_and_Region_with_workshop_wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_vehicle_sold_to_New_Owner_of_ZONE_and_Region_with_Day_wise" time="1.011"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Fresh_of_ZONE_and_Region_with_Day_wise" time="1.016">
    <failure message="expected [0] but found [416]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [0] but found [416]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_Fresh_of_ZONE_and_Region_with_Day_wise(SMR_Due_Date_Wise_Central.java:840)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Fresh_of_ZONE_and_Region_with_Day_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Fresh_of_ZONE_and_Region_with_service_type_wise" time="0.000">
    <failure message="expected [0] but found [416]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [0] but found [416]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_Fresh_of_ZONE_and_Region_with_service_type_wise(SMR_Due_Date_Wise_Central.java:846)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Fresh_of_ZONE_and_Region_with_service_type_wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_vehicle_sold_to_New_Owner_of_ZONE_and_Region_with_service_type_wise" time="0.010"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Refuse_for_service_at_OWN_of_ZONE_and_Region_with_Dealer_Parent_Group_Wise" time="0.001"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_pending_Fresh_of_ZONE_and_Region_with_Dealer_Parent_Group_Wise" time="0.000">
    <failure message="expected [30886] but found [30471]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [30886] but found [30471]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_pending_Fresh_of_ZONE_and_Region_with_Dealer_Parent_Group_Wise(SMR_Due_Date_Wise_Central.java:852)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_pending_Fresh_of_ZONE_and_Region_with_Dealer_Parent_Group_Wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Refuse_for_service_at_OWN_of_ZONE_and_Region_with_WorkshoP_Wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_pending_Fresh_of_ZONE_and_Region_with_WorkshoP_Wise" time="0.000">
    <failure message="expected [30885] but found [30471]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [30885] but found [30471]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_pending_Fresh_of_ZONE_and_Region_with_WorkshoP_Wise(SMR_Due_Date_Wise_Central.java:858)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_pending_Fresh_of_ZONE_and_Region_with_WorkshoP_Wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_pending_Fresh_of_ZONE_and_Region_with_Day_Wise" time="0.000">
    <failure message="expected [30883] but found [30471]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [30883] but found [30471]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_pending_Fresh_of_ZONE_and_Region_with_Day_Wise(SMR_Due_Date_Wise_Central.java:864)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_pending_Fresh_of_ZONE_and_Region_with_Day_Wise -->
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Refuse_for_service_at_OWN_of_ZONE_and_Region_with_Day_Wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_Refuse_for_service_at_OWN_of_ZONE_and_Region_with_service_type_Wise" time="0.000"/>
  <system-out/>
  <testcase classname="merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central" name="Compare_pending_Fresh_of_ZONE_and_Region_with_service_type_Wise" time="0.000">
    <failure message="expected [30881] but found [30471]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [30881] but found [30471]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central.Compare_pending_Fresh_of_ZONE_and_Region_with_service_type_Wise(SMR_Due_Date_Wise_Central.java:870)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_pending_Fresh_of_ZONE_and_Region_with_service_type_Wise -->
  <system-out/>
</testsuite> <!-- merge_SMR_Central_Zone.SMR_Due_Date_Wise_Central -->
