<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7SBKKJ1" failures="1" tests="7" name="My_Leads_Data.Call_Dispostion_Of_Today_Booking" time="180.165" errors="0" timestamp="2024-09-30T11:58:32 IST" skipped="0">
  <testcase classname="My_Leads_Data.Call_Dispostion_Of_Today_Booking" name="Username" time="2.165"/>
  <system-out/>
  <testcase classname="My_Leads_Data.Call_Dispostion_Of_Today_Booking" name="Password" time="3.209"/>
  <system-out/>
  <testcase classname="My_Leads_Data.Call_Dispostion_Of_Today_Booking" name="Captcha" time="3.121"/>
  <system-out/>
  <testcase classname="My_Leads_Data.Call_Dispostion_Of_Today_Booking" name="SUBMIT_Button" time="15.079"/>
  <system-out/>
  <testcase classname="My_Leads_Data.Call_Dispostion_Of_Today_Booking" name="Click_On_MY_Leads" time="15.088"/>
  <system-out/>
  <testcase classname="My_Leads_Data.Call_Dispostion_Of_Today_Booking" name="click_Today_Booking" time="70.606"/>
  <system-out/>
  <testcase classname="My_Leads_Data.Call_Dispostion_Of_Today_Booking" name="Click_On_need_For_Reshudle_in_NO" time="70.897">
    <failure message="Customer with name SACHIN KUMAR SHARMA not found after clicking &#039;Reschedule&#039;in Today booking&#039;." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Customer with name SACHIN KUMAR SHARMA not found after clicking 'Reschedule'in Today booking'.
at org.testng.Assert.fail(Assert.java:99)
at My_Leads_Data.Call_Dispostion_Of_Today_Booking.Click_On_need_For_Reshudle_in_NO(Call_Dispostion_Of_Today_Booking.java:371)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Click_On_need_For_Reshudle_in_NO -->
  <system-out/>
</testsuite> <!-- My_Leads_Data.Call_Dispostion_Of_Today_Booking -->
